### ISSUE TITLE
Share new datasets

### ISSUE THREAD

**Issue by Luffy03** [openmedlab/Awesome-Medical-Dataset#4]
Hi, thank you very much for your dedicated efforts in this field!
Would you please help us share the new datasets introduced by our CVPR 2024 extension paper? It would help us a lot!

Official website: https://github.com/Luffy03/Large-Scale-Medical
Paper link: https://arxiv.org/abs/2410.09890

Dataset PreCT-160K (whole body): https://huggingface.co/datasets/Luffy503/PreCT-160K
Description: 160K CT volumes (42M slices) for pre-training

Dataset VoComni (whole body): https://huggingface.co/datasets/Luffy503/VoComni
Description: 20K CT volumes for segmentation, with 20 organ & tumor classes of labels

Dataset VoCovid (chest): https://huggingface.co/datasets/Luffy503/VoCovid
Description: 2871 CT volumes for semi-supervised COVID segmentation

**Comment by MengzhangLI** [comment]
Hi, first sorry for late congrats to your acceptance of CVPR'2024 extension.

I would try to record these datasets as soon as possible.

Our documents usually follow this template: 

https://github.com/openmedlab/Awesome-Medical-Dataset/blob/main/resources/template.md.

Due to I am unfamiliar with your dataset, it is very helpful if you can help me with statistics such as "Dataset Meta Information", "Resolution Details", "Label Information Statistics" and "File Structure". 

Best,

**Comment by Luffy03** [comment]
Thank you very much for your kind reply and I will check the statistics as soon as possible

**Comment by Luffy03** [comment]
Dear Dr. Li, I have attached a markdown file and a figure to depict this dataset. You may need to rename the figure as 'vocomni.png' and put it in the right path.
I am not sure whether they fix the desired formats. Would you please take a look at them? Thank you very much!
[VoComni.md](https://github.com/user-attachments/files/17427338/VoComni.md)
![vocomni](https://github.com/user-attachments/assets/35163d5a-36a6-4a39-8929-1267b3c829c1)
